### ISSUE TITLE
PF2 item mystification not working properly when Token Hotbar is loaded

### ISSUE THREAD

**Issue by Weissrolf** [janssen-io/foundry-tokenhotbar-js#4] opened 2021-12-12 14:19 UTC
When Token Hotbar is run then pressing the "Mystify Item" button does not update the PF2E char sheet, it needs to be closed/reopened. Disabling Token Hotbar fixes this immediately.

**Comment by janssen-io** [comment] 2021-12-14 10:46
I'm not familair with PF2E, is 'Mystify Item' core functionality or part from another module? If the latter, than what module adds this functionality?

What should change on the character sheet? I'm trying to reproduce the issue, but I'm not sure what to look for. 😅

**Comment by Weissrolf** [comment] 2021-12-14 11:28
Mystify Item is a core functionality of the PF2E system. It changes an item's name to a name that does not reveal the item properties (mostly used for magical items).

When Token Hotbar breaks the functionality then you have to close and reopen the character sheet to see the changes. When it functions properly then the char sheet is updated immediately without need to reopen.

Similar to the macro bug I reported this currently is working (with only Token Hotbar and Custom Hotbar being enabled). So it likely depends on the same code breaking condition that causes the other bug. I will keep an eye on trying to better reproduce the condition.

**Comment by janssen-io** [comment] 2021-12-14 14:08
Thanks for the additional information! This definitely helps with analyzing the issue. :)

**Comment by janssen-io** [comment] 2022-01-04 16:31
When I change the mystification status with Token Hotbar enabled, it seems to change it directly on the character sheet. For both the person changing it and the other player(s) who have the sheet open. So I'm afraid I'm also unable to reproduce this issue. :(

Do you see any errors in the console when this happens? Also, is this in the browser (if so which one) or the Foundry VTT client?

**Comment by Weissrolf** [comment] 2022-01-05 00:48
Same here now. Maybe some change in the PF2E system.

**Comment by janssen-io** [comment] 2022-01-07 10:48
I will close this until it pops up again. :)

**Closed as completed by janssen-io** 2022-01-07 10:48 UTC
